spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/alfalibrary
    username: postgres
    password: 2316
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    enabled: false
